version: '3.9'

services:

  app:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - projects:/data/db

volumes:
  projects:
